config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

#URL「top」にアクセスしたとき、homesコントローラのtopアクションが呼び出されるように設定
get 'top' => 'homes#top'
resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
#Listモデルに画像を扱うためのimageカラムが追記されたかのように扱うことができる
  has_one_attached :image
  
  #バリデーションの設定
  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
#define=定義する　
#topページを表示するためのアクション
  def top
    
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    #Viewへ渡すためのインスタンス変数にからのModelオブジェクトを生成
    @list = List.new
  end

  def create
    #データを受け取り新規登録するためのインスタンス作成
    @list = List.new(list_params)
    #データをデータベースに保存するためのsaveメソッド実行
    if @list.save
      #フラッシュメッセージを定義、詳細画面へリダイレクト
      flash[:notice] = "投稿に成功しました。"
    #詳細画面へリダイレクト
      redirect_to list_path(@list.id)
    else
    #フラッシュメッセージを定義、new.html.erbを描画
    flash.now[:alert] = "投稿に失敗しました。" #キーをalertに変更
     render :new
    end
  end

  def index
    #indexアクションは一覧画面用のアクションとして定義
    #一覧画面には投稿したList全てを表示させるので、全てのデータを取得する記述
    @lists =List.all
  end

  def show
    #レコードを1件だけ取得するので、インスタンス変数名は単数形の@list
    @list = List.find(params[:id])
  end

  def edit
    #投稿済みのデータを編集するので、保存されているデータが必要
    #findメソッドを用いて、データを取得
    @list = List.find(params[:id])
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to list_path(list.id)
  end

  def destroy
    list = List.find(params[:id]) #データ(レコード)を1件取得
    list.destroy #データ(レコード)を削除
    redirect_to '/lists'  #投稿一覧画面へリダイレクト
  end


private
#ストロングパラメータ
  def list_params
   params.require(:list).permit(:title, :body, :image)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<% #[New File」を押すことで新規ファイルを作成 %>
<h1>ここはTopページです</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <main>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"<%= message %></div>
    <% end %>
    <%= yield %>
  </main>
</html>

app/views/lists/edit.html.erb
<h1>編集画面</h1>
<%# form_withを利用すると、インスタンス変数を渡すだけで、
インスタンス変数内のモデルを解読して、投稿したタイトルと内容を代入 %>
<%= form_with model: @list do |f| %>

<h4>タイトル</h4>
<%= f.text_field :title %>

<h4>本文</h4>
<%= f.text_area :body %>

<%= f.submit '保存' %>

<% end %>

app/views/lists/index.html.erb
<h1>投稿一覧</h1>
<%# @lists.eachと記述することで、Listレコードの数だけ繰り返し処理を行う %>
<%# 各レコードの内容は、listという変数に格納 %>
<% @lists.each do |list| %>

 <p>タイトル<p>
 <%# list.titleと記述することで、投稿のタイトルが表示 %>
 <%# リンク先URLは、/lists/:idの「:idに該当する部分」を指定 %>
 <span>
   <%= link_to list.title, list_path(list.id) %>
 </span>

 <p>画像</p>
<%= image_tag list.image, size: "200×200" %>
<% end %>

app/views/lists/new.html.erb
<h1>新規投稿</h1>

<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
 </ul>
<% end %>
<!-- form_with部分 -->
<!-- List.newと定義することで、Listモデルの情報をもとに
新しくオブジェクトが作成され、Listモデルに存在するtitle・bodyが格納 -->
<%= form_with model: @list, url: '/lists', method: :post do |f| %>
    <h4>タイトル</h4>
<!-- タイトルを入力する部分 -->
    <%= f.text_field :title %>
    <h4>本文</h4>
<!-- 投稿を入力する部分  -->
    <%=f.text_area :body %>
<!-- 画像をを追加する部分-->
    <h4>画像</h4>
<!-- accept: "image/*"を使い、画像ファイルしか投稿できない-->
    <%=f.file_field :image, accept: "image/*" %>
<!-- 投稿ボタン  -->
    <%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<%# 詳細画面　%>
<h2>タイトル</h2>
<p><%= @list.title %></p>

<h2>本文</h2>
<p><%= @list.body %></p>
<%# 編集画面へ遷移するリンクを設定 %>
<%= link_to "編集", edit_list_path(@list.id) %>

<h2>画像</h2>
<%= image_tag @list.image, size: "300×300" %>

<%= link_to "編集", edit_list_path(@list.id) %>
<%# 誤って「削除」をクリックしてしまった場合に備えて、
data-confirmを用いて削除確認ダイアログも表示されるように設定 %>
<%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>